const hikingSummerList = [
    "Backpack",
    "Raincover",
    "Trekking Poles",
    "Headlamp",
    "GoPro",
    "GPS Satellite Tracker",
    "Pocket Knife",
    "Waterproof Bag",
    "Sleep pad",
    "Tent",
    "Stove",
    "Cooking Set",
    "Bear Can",
    "Hydration System",
    "Water Sterlizer",
    "Zip-off Pants",
    "Shorts",
    "Lightweight Shirts",
    "Rain Jacket",
    "Waterproof Hiking Boots",
    "Sandals",
    "Hat",
    "Lightweight Gloves",
    "Lightweight Jacket",
    "Sunglasses",
    "Towels",
    "Bugspray",
    "Sunscreen",
    "Socks",
    "Toiletries",
    "Toilet Paper",
    "Map",
    "Compass",
    "First Aid Kit",
    "Headlamp with Batteries"
  ];
  const hikingWinterList = [
    "Backpack",
    "Raincover",
    "Trekking Poles",
    "Headlamp",
    "GoPro",
    "GPS Satellite Tracker",
    "Pocket Knife",
    "Waterproof Bag",
    "Sleep pad",
    "Tent",
    "Stove",
    "Cooking Set",
    "Bear Can",
    "Hydration System",
    "Water Sterlizer",
    "Zip-off Pants",
    "Shorts",
    "Lightweight Shirts",
    "Rain Jacket",
    "Waterproof Hiking Boots",
    "Sandals",
    "Hat",
    "Lightweight Gloves",
    "Lightweight Jacket",
    "Sunglasses",
    "Towels",
    "Bugspray",
    "Sunscreen",
    "Socks",
    "Toiletries",
    "Toilet Paper",
    "Warm Socks",
    "Insulated Hiking Boots",
    "High Gaiters",
    "Heavy Wool Hat",
    "Waterproof Gloves",
    "Insulated Coat with Hood",
    "Hard Shell Pants",
    "Fleece Vest",
    "Fleece Jacket",
    "Long Underwear",
    "Spare Clothing",
    "Map",
    "Compass",
    "First Ait Kit",
    "Headlamp with Batteries",
    "Microspikes",
    "Snowshoes",
    "Face Mask"
  ];
  const surfingList = [
    "Surfboards",
    "Travel Bag",
    "Wax",
    "Fins",
    "Leashes",
    "Wetsuit",
    "Rashguard",
    "Boardshorts",
    "T-shirts",
    "Sunglasses",
    "Hat",
    "Towels",
    "Backpack",
    "Waterproof Watch",
    "Sunscreen",
    "Vaseline",
    "Sandals",
    "Water Bottle",
    "Small First Aid Kit",
    "Go-Pro",
    "Bathing Suits"
  ];
  const bikingSummerList = [
    "Rearlight",
    "Fenders",
    "Front and Rear Rack",
    "Panniers",
    "Helmet",
    "Lightweight Jacket",
    "Watch",
    "Road ID",
    "Bicycle Shoes",
    "Pant Leg Protectors",
    "Water Bottles",
    "Tent",
    "Toiletry Kit",
    "T-shirts",
    "Sweatpants",
    "Clothes",
    "Sunglasses",
    "Knife",
    "Patch Kit",
    "Flashlight",
    "Tire Levers",
    "Bungee Cord",
    "Spork",
    "Food",
    "Cable Lock and Key",
    "Pedal Wrench",
    "Shorts",
    "Sandals"
  ];
  const bikingWinterList = [
    "Rearlight",
    "Fenders",
    "Front and Rear Rack",
    "Panniers",
    "Helmet",
    "Lightweight Jacket",
    "Watch",
    "Road ID",
    "Bicycle Shoes",
    "Pant Leg Protectors",
    "Water Bottles",
    "Tent",
    "Toiletry Kit",
    "T-shirts",
    "Sweatpants",
    "Clothes",
    "Sunglasses",
    "Knife",
    "Patch Kit",
    "Flashlight",
    "Tire Levers",
    "Bungee Cord",
    "Spork",
    "Food",
    "Cable Lock and Key",
    "Pedal Wrench",
    "Snow Jacket",
    "Ski Pants",
    "Ski Gloves",
    "Ski Goggles",
    "Arm Warmers",
    "Heavy Socks",
    "Heavy Hat",
    "Face Mask",
    "Long Underwear"
  ];
  const campingWinterList = [
    "Map",
    "Compass",
    "GPS",
    "Sunscreen",
    "Sunglasses",
    "Lip Balm",
    "HeadLamp with Batteries",
    "First Ait Kit",
    "Matches and Lighter",
    "Fire Starter",
    "Waterproof Container",
    "Knife/MultiTool",
    "Stove Kit",
    "Food",
    "Hydrations System",
    "Water Filter",
    "Tent",
    "Tarp",
    "Reflective Blanket",
    "Packable Lantern",
    "Sleeping Bag",
    "Cookset",
    "Blankets",
    "Food Storage Containers",
    "Pot Grabber",
    "Playing Cards",
    "Clothing",
    "Toiletry Kit",
    "Bug Spray",
    "Hand Sanitizer",
    "Folding Chairs",
    "Heavy Coat",
    "Fleece Vest/Jacket",
    "Heavy Pants",
    "Heavy Hat",
    "Gloves",
    "Trekking Poles",
    "Sleeping Bag Liners",
    "Gloves",
    "Hand Warmers",
    "Insulated Boots",
    "Heavy Socks"
  ];
  const campingSummerList = [
    "Map",
    "Compass",
    "GPS",
    "Sunscreen",
    "Sunglasses",
    "Lip Balm",
    "HeadLamp with Batteries",
    "First Ait Kit",
    "Matches and Lighter",
    "Fire Starter",
    "Waterproof Container",
    "Knife/MultiTool",
    "Stove Kit",
    "Food",
    "Hydrations System",
    "Water Filter",
    "Tent",
    "Tarp",
    "Reflective Blanket",
    "Packable Lantern",
    "Sleeping Bag",
    "Cookset",
    "Blankets",
    "Food Storage Containers",
    "Pot Grabber",
    "Playing Cards",
    "Clothing",
    "Toiletry Kit",
    "Bug Spray",
    "Hand Sanitizer",
    "Folding Chairs",
    "Bathing Suits",
    "Lightweight Gloves",
    "Sandals",
    "Walking Shoes",
    "Lightweight Hat",
    "Lightweight Rainjacket"
  ];
  const raftingSummerList = [
    "Clothes",
    "Dry Bag",
    "Food",
    "Toiletries",
    "Flashlight",
    "Headlamp with Batteries",
    "Playing Cards",
    "Extra Bag for Wet Clothes",
    "Duct Tape",
    "Bandana",
    "Bug Spray",
    "Hand Sanitizer",
    "Towel",
    "Bathing Suit",
    "Synthetic Shirt",
    "Sneakers",
    "Sandalas with Straps",
    "Hat",
    "Sunglasses with strap",
    "Water Bottles",
    "Sunscreen",
    "River Shoes"
  ];
  const raftingWinterList = [
    "Clothes",
    "Dry Bag",
    "Food",
    "Toiletries",
    "Flashlight",
    "Headlamp with Batteries",
    "Playing Cards",
    "Extra Bag for Wet Clothes",
    "Duct Tape",
    "Bandana",
    "Bug Spray",
    "Hand Sanitizer",
    "Towel",
    "Sunglasses with strap",
    "Water Bottles",
    "Sunscreen",
    "Windproof/Waterproof Jacket",
    "Warm Hat",
    "Synthetic/Wool Hat",
    "Synthetic/Wool Long-Sleeved Shirts",
    "Synthetic/Wool Long Underwear",
    "Windproof/Waterproof Pants",
    "Wetsuit"
  ];
  const kayakingSummerList = [
    "Kayak",
    "Paddle",
    "Personal Floatation Device",
    "Bilge Pump",
    "Dry Bag",
    "Headlamp with Batteries",
    "Whistle",
    "Paddle Float",
    "Paddling Knife",
    "Towline",
    "Map in Waterproof Case",
    "Watch",
    "Weather Radio",
    "Float Bag",
    "Paddle Leash",
    "Compass",
    "Large Sponge",
    "Emergency Flares",
    "GPS",
    "2-way Radios",
    "Sunglasses",
    "Sunscreen",
    "Food",
    "Bug Spray",
    "Bungee Cords",
    "Baling Wire",
    "Replacement Rudder Parts",
    "Multi-tool",
    "Static Deck Line",
    "Sealant",
    "Water Treatment",
    "Toilet Paper",
    "Hand Sanitizer",
    "Lip Balm",
    "Water Bottles",
    "Matches/Fire Starter",
    "Tent",
    "Swimwear",
    "Rashguard",
    "Neoprene Shoes",
    "Hat",
    "Cap Retainer Leash",
    "Bandana/Buff",
    "Paddling Gloves",
    "Lightweight Jacket",
    "Rain Jacket",
    "Sandals"
  ];
  const kayakingWinterList = [
    "Kayak",
    "Paddle",
    "Personal Floatation Device",
    "Bilge Pump",
    "Dry Bag",
    "Headlamp with Batteries",
    "Whistle",
    "Paddle Float",
    "Paddling Knife",
    "Towline",
    "Map in Waterproof Case",
    "Watch",
    "Weather Radio",
    "Float Bag",
    "Paddle Leash",
    "Compass",
    "Large Sponge",
    "Emergency Flares",
    "GPS",
    "2-way Radios",
    "Sunglasses",
    "Sunscreen",
    "Food",
    "Bug Spray",
    "Bungee Cords",
    "Baling Wire",
    "Replacement Rudder Parts",
    "Multi-tool",
    "Static Deck Line",
    "Sealant",
    "Water Treatment",
    "Toilet Paper",
    "Hand Sanitizer",
    "Lip Balm",
    "Water Bottles",
    "Matches/Fire Starter",
    "Tent",
    "Drysuit",
    "Long Underwear",
    "Wool Socks",
    "Pogies",
    "Wool Synthetic Cap"
  ];
  